# Generated by Django 6.0.6 on 2026-06-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('directors', '0001_initial'),
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Plot / description of the movie')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('youtube_link', models.URLField(blank=True, help_text='Trailer / YouTube URL')),
                ('average_rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='categories.category')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='directors.director')),
                ('writers', models.ManyToManyField(blank=True, related_name='movies', to='writers.writer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
