# Generated by Django 6.0.6 on 2026-06-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (alternative to upload)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (multipart/form-data)', null=True, upload_to='movies/'),
        ),
    ]
